services:
  purrbalancer:
    build:
      context: ./PurrBalancer
      dockerfile: dockerfile
    ports:
      - "127.0.0.1:5000:8080"
    restart: unless-stopped

  purrlay:
    build:
      context: ./PurrLay
      dockerfile: dockerfile
    ports:
      - "127.0.0.1:5001:8081"
      - "127.0.0.1:7777:7777/udp"
      - "127.0.0.1:5003:6942"
    environment:
      - HOST_SSL=true
      - HOST_REGION=nj-us
      - HOST_DOMAIN=resonance-relay.bchen.dev
      - HOST_PORT=8081
      - HOST_ENDPOINT=http://purrlay:8081
      - BALANCER_URL=http://purrbalancer:8080
    depends_on:
      - purrbalancer
    restart: unless-stopped
